# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Center for Community Dialog and Change - Conference Website
email: "contact@ccdc.in"
telephone: "080 23692168"
description: >- # this means to ignore newlines until "baseurl:"
  Website for CCDC's upcoming conference in December 2024
address: >-
  A2 204, Shriram Whitehouse Apartments,
  15th Cross, 6th Main, RT Nagar,
  Bangalore 560032, Karnataka, India

#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

repository: "ccdcin/ccdcin.github.io"

registration_link: "https://forms.google.com/"
conference_dates: "13th - 15th December"
venue: "Indian Social Institute"
debug: true

header_pages:
  - about.md
  - schedule.html
  - speakers.md

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

sass:
  sass_dir: _sass

social_links:
  twitter: https://x.com/
  instagram: https://www.instagram.com/
  facebook: https://www.facebook.com/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
